@baseUri = http://localhost:8000
@contentType = application/json

########
GET {{baseUri}}/regions?skip=0 HTTP/1.1

########
POST {{baseUri}}/regions HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "England"
}

########
PATCH {{baseUri}}/regions/3 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Italy",
    "content": "Italy is located in south-western europe."
}