@baseUri = http://localhost:8000
@contentType = application/json

########
GET {{baseUri}}/scopes?skip=0 HTTP/1.1

########
POST {{baseUri}}/scopes HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Sports"
}

########
PATCH {{baseUri}}/scopes/3 HTTP/1.1
Content-Type: {{contentType}}

{
    "content": "What is sports?"
}