@baseUri = http://localhost:8000
@contentType = application/json

########
GET {{baseUri}}/teams?skip=0 HTTP/1.1

########
GET {{baseUri}}/teams/1 HTTP/1.1

########
POST {{baseUri}}/teams HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Real Madrid FC",
    "symbol": "RM",
    "content": "Real Madrid CF",
    "categoryId": 1
}

########
PATCH {{baseUri}}/teams/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Real Madrid FC",
    "symbol": "Real Madrid",
    "content": "Real Madrid FC is football club in Madrid, Spain."
}

########
DELETE {{baseUri}}/teams/1 HTTP/1.1